# Generated by Django 6.0.2 on 2026-04-28 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
