# Generated by Django 6.0.2 on 2026-05-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_message_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='input_token',
            new_name='input_tokens',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='output_token',
            new_name='output_tokens',
        ),
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
